version: '3'
services:
  web:
    build: .
    ports:
      - "623:80"
    volumes:
      - ./src:/srv/try-haxe/src
      # - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "service apache2 start && tail -f /dev/null"
