version: '3'
services:
  web:
    build: .
    ports:
      - "623:80"
    volumes:
      - ./www:/var/www/html
      - ./hashlink-bin:/srv/try-haxe/hashlink
      - ./lixSetup:/srv/try-haxe/lixSetup
      - ./programs:/var/www/html/tmp
      # - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "service apache2 start && tail -f /dev/null"
    privileged: true
